### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by MarkusTeufelberger** [br0ns/ddmin#1]
Could you please add a license to this code? Thanks a lot! :-)

**Comment by br0ns** [comment]
Sure.  Any suggestions?

**Comment by MarkusTeufelberger** [comment]
It's really up to you, ISC or MIT would be short and quite permissive for example... http://choosealicense.com/licenses/ has a nice overview.

**Comment by br0ns** [comment]
Alright, MIT it is.
